src/composables/echarts.ts
fix:cannot re-render if dom is deleted
If the chart is opened in the pop-up window, opening the chart again will not display properly.
=> fix:cannot re-render if dom is deleted <Update echarts.ts>

src/views/dashboard/analysis/components/BottomPart/index.vue
分析页的时间线和表格内容较多时会超出card边界，试着去掉限制h-360px的div后可以自适应高度。
=> fix: remove height limit h-360px

src/utils/router/menu.ts
如：
路由1：/setting/product
路由2：/product/another
路由3：/yet-another/product-list
在路由1激活时，菜单中路由2，3所对应菜单项会被错误展开
=> fix(components): 修复路由在path中包含重复路单词径菜单时，被激活会错误展开

src/utils/router/menu.ts
If the backend passes in an empty list `children: []`, some elements of the navigation bar will not be clickable
=> fix(projects): the length of routes children list should greater than 0

src/service/request/request.ts
0.9.8
把 `src/service/request/request.ts` 中的 `handleDelete` 方法的参数 `AxiosRequestConfig` 从**必要**改为_可选_
Closes #
=> fix(utils): make AxiosRequestConfig optional for request.handleDelete()

src/App.vue, src/layouts/common/global-header/components/global-breadcrumb.vue, src/layouts/common/global-header/components/header-menu.vue, src/layouts/common/global-header/components/index.ts, src/layouts/common/global-header/components/toggle-lang.vue, src/layouts/common/global-header/index.vue, src/layouts/common/global-logo/index.vue, src/layouts/common/global-sider/components/vertical-mix-sider/index.vue, src/layouts/common/global-sider/components/vertical-sider/components/vertical-menu.vue, src/layouts/common/global-tab/components/tab-detail/index.vue, src/locales/i18n.ts, src/router/guard/index.ts, src/router/modules/dashboard.ts, src/store/modules/tab/helpers.ts, src/typings/route.d.ts, src/typings/storage.d.ts, src/typings/system.d.ts, src/utils/router/breadcrumb.ts, src/utils/router/menu.ts
0.9.9
完善i18n功能，菜单（水平和竖直），tab，面包屑，文档title都可以根据语言切换
在router/modules的每个模块中，meta定义i18nTitle字段，当i18nTitle和title同时存在，i18nTitle优先
详情可以参考 router/modules/dashboard.ts
=> feat(projects): 增加i18n支持翻译菜单,tab,title

.vscode/settings.json, src/components/common/dark-mode-switch.vue
0.9.9
Use [View Transition AP](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) 增加切换主题的过度效果
=> feat(projects): 增加主题切换过渡效果

tsconfig.json
See: https://vuejs.org/guide/typescript/overview.html#configuring-tsconfig-json
I noticed that the Vue documentation mentions some details about configuring tsconfig.json, including various options and project references. In particular, there is an important configuration option mentioned: compilerOptions.isolatedModules, which is set to true because Vite uses esbuild for TypeScript transpilation and is subject to single-file transpile limitations.
However, I noticed that this option is not configured in our project's tsconfig.json. 
Closes #
=> fix(projects): tsconfig missing isolatedModules

README.md
你好!
我很喜欢这个项目, 也很高兴能向您提交这个PR, 我把项目原来的通过 Docker Hub 构建镜像的方式改为了本地构建.
感谢您的审阅, 期待您的反馈.
谢谢~
v0.10.3
1. 在 Docker 部署过程运行命令`docker run --name soybean -p 80:80 -d soybeanjs/soybean-admin:v0.9.6`失败, 所以改为通过本地Dockerfile构建 Docker 镜像`docker build -t soybean-admin-image -f docker/Dockerfile .`, 然后运行镜像`docker run -d -p 80:80 soybean-admin-image`
2. 更新 git hooks 初始化命令为`pnpm soy init-simple-git-hooks`
否
Closes #
=> Update Docker deployment method and git hooks init command

src/store/modules/route/index.ts, src/store/modules/route/shared.ts
This function sorts the routes by their meta.order property, which is a number. If the meta.order property is missing or
invalid, it is treated as 0. The routes with lower meta.order values are placed before the routes with higher meta.order
values. The function also sorts the children routes recursively, if any.
v1.0-beta
Support routing sorting
否
=> feat(router): add sortRoutesByOrder function

env.config.ts
proxy代理前缀冲突，导致代理后，请求一直发送默认地址
v1.0-beta
修复代理请求，都指向默认地址的问题
否
=> fix(projects): default proxy prefix

src/store/modules/tab/shared.ts, src/typings/app.d.ts
Fix the issue of abnormal tab display when the parent menu has a localIcon and the child menu does not have one
=> fix(projects): Fix the issue of tab error displaying parent localIcon

packages/hooks/src/use-table.ts, src/hooks/common/table.ts, src/locales/langs/en-us.ts, src/locales/langs/zh-cn.ts, src/typings/app.d.ts, src/typings/naive-ui.d.ts, src/views/manage/user/index.vue
- 添加表格分页 `prefix` 是否显示总条数选项: `showTotal`
- 使用 `pagination` 对象分页，`showTotal` 为 `false` 时，`pagination` 不添加 `prefix`
- 使用 `mobilePagination` 情况下，排版问题，默认不显示，它 `prefix:undefined`
- 启用页面为 `manage/user/index`
=> feat(projects): add table showTotal options

src/store/modules/tab/shared.ts, src/typings/app.d.ts, src/typings/router.d.ts
- 修复过滤 Tab `fixedIndex` 为`null`的情况
=> fix(projects): fix tab fixedIndex as null case

src/components/advanced/table-column-setting.vue
表格列设置中，使用了拖动排序的功能并且提供了拖动块，并且拖动块在鼠标 `hover` 时显示 `move` 图标，在列标题的部分鼠标是不变化的
但目前整个单元格都可以进行拖动操作，这与用户预期不同，并且标题的部分没有占满行剩余空间，对于较短标题在点击单元格右侧空白处不会触发点击事件，见下图
> 其中红色是可以拖动的区域，蓝色是点击时触发的区域
- 放大拖动块的区域和单元格同高度，在鼠标变化为 `move` 时，都可以对单元格进行拖动
- 标题区域撑满行剩余空间，所有标题的部分都可以进行点击
- 添加拖动动画，用户体验会更好
- 使用 `filter` 对 `checkbox` 元素进行过滤（添加类 `.none_draggable`），做到只有移动拖动块时单元格会进行拖动排序，拖动标题区域时不会触发排序
=> optimize(components): accuracy draggable area for TableColumnSetting with animation

src/components/custom/button-icon.vue, src/layouts/modules/global-search/components/search-modal.vue, src/layouts/modules/global-search/components/search-result.vue
close #466 
1、控制台报错是因为阻止默认事件有点问题，可能是事件传递在vue中有更新？我看只有里面的click会触发这个`enter`事件，所以直接移里面去做了
2、除此之外回车触发跳转后弹窗会被重新打开，经过测试发现是`header`的按钮持续聚焦导致的，在按钮聚焦的时候只要在页面内按了回车都会导致按钮被触发点击事件，结果思考还是建议取消`ButtonIcon`组件内按钮的可聚焦状态，这样在不影响现有功能的情况下，有利于减少某些页面内绑定了回车事件时可能出现的bug
=> fix(components): 修复搜索回车不关闭弹框、点击无法跳转的问题

src/service/request/index.ts
场景: 请求失败后弹出模态框再登出用户
bug：用户按Esc, 弹窗消失，但是没有触发登出用户操作。
=> fix(utils): modalLogout bug when esc is pressed

index.html
手机开启深色模式后，自带的浏览器打开页面会被影响
修复前为
修复后为
=> fix(projects): mobile browser theme bug

.vscode/settings.json
该实验配置在`8.57.0`以后已弃用，改为 `eslint.useFlatConfig`
=> chore(projects): Fix deprecated configuration config

src/store/modules/route/shared.ts, src/typings/router.d.ts
修改菜单栏的图标时( naive UI 的 Menu 组件)， 使用组件的 `theme-overrides` 方法修改图标大小无效。
原因：路由初始化使用 SvgIconVNode 方法，在 svg 的**根标签上注入了 `font-size`** 属性。导致 theme-overrides 在父元素设置的 `font-size` 无法影响到 svg 元素。
- 考虑到向前兼容的问题，RouteMeta 添加可选属性 iconFontSize，以控制图标大小
=> optimize(projects):  supports custom menu icon sizes

src/hooks/common/table.ts
防止接口的分页大小返回0的时候页面卡死，考虑到部分系统无返回该内容、没有使用组件库的分页器或是有对应的ORM做了这个限制，所以就不放到`useTableHook`里了，在`transformer`里做一个简单的拦截+提示就行，避免这个`size`变为“魔法值”
=> fix(hooks): prevent program freezing when pagesize returns 0

src/layouts/modules/theme-drawer/modules/dark-mode.vue, src/locales/langs/en-us.ts, src/locales/langs/zh-cn.ts, src/store/modules/theme/index.ts, src/store/modules/theme/shared.ts, src/styles/css/global.css, src/theme/settings.ts, src/typings/app.d.ts
在theme的shared.ts里，因为灰度模式与色弱模式可以重合使用，如果要沿用类名需要增加**两个**新的类名去支持新的**一个**使用`filter`的css功能，也不可避免的要使用多个 `if` 去判断最终选用哪个，这种做法不优雅，所以我将原先使用类名控制灰度模式的部分删掉了，改为在js代码里直接控制
=> feat(projects): add color fading mode.close #567

packages/scripts/src/locales/index.ts
依据Apache Doris的社区规范增加更多commit type
https://doris.apache.org/zh-CN/community/how-to-contribute/commit-format-specification
=> feat(projects): Add more commit types according to Apache specifications

packages/alova/package.json, packages/alova/src/fetch.ts, packages/alova/src/mock.ts, pnpm-lock.yaml, src/serviceAlova/api/auth.ts, src/serviceAlova/api/index.ts, src/serviceAlova/api/route.ts, src/serviceAlova/mocks/feature-users-20241014.ts, src/serviceAlova/request/index.ts, src/serviceAlova/request/shared.ts, src/serviceAlova/request/type.ts
优化了`@sa/alova`子包，具体如下：
1. 新增`@sa/alova/fetch`、`@sa/alova/mock`导出，添加了mock能力
2. 新增`src/serviceAlova`，当用户选择使用alova时可直接上手使用
=> feat: optimistic subpackage `@sa/alova`

src/plugins/app.ts
1. 支持定时检测系统更新，默认时长为3分钟
2. 优化代码，不需要检测更新的时候完全不监听可见性切换事件与不开启定时器
=> feat(projects): support scheduled detection and update system.

src/views/_builtin/login/modules/pwd-login.vue
=> fix: #697 multiple calls to the login API when clicking quickly

src/constants/app.ts, src/plugins/loading.ts, src/store/modules/theme/index.ts, src/store/modules/theme/shared.ts, src/typings/storage.d.ts
=> feat(projects): support loading page dark mode adaptation. close #695

src/hooks/common/router.ts, src/store/modules/tab/index.ts, src/typings/app.d.ts
=> feat(projects): support replaceTab. 

package.json
Node 18.20.0以下的版本,执行`pnpm lint` 会报错，`@soybeanjs/eslint-config` 中的依赖 `eslint-plugin-unicorn` 使用了
```js
// /node_modules/eslint-plugin-unicorn/index.js  第4行
import packageJson from  './package.json' with {type: 'json'};
```
=> build(deps): Restrict the minimum Node.js version.

packages/materials/src/libs/page-tab/index.vue, src/store/modules/tab/index.ts
- In Vue 3, @click.stop can only prevent click events from bubbling, not pointer down events, because pointer down occurs before click and is a lower-level event.
- When closing the ‘about’ tab, it should jump to the next tab instead of jumping to the last tab in the tab array.
when close 'abot' happened:
should be like:
- When closing a tab that is not the current one, it should not jump, instead of jumping to the last tab in the tab array.
when close '500' happened:
should be like:
- Optimized `removeTab` to use index-based removal for better efficiency.
- Ensured the next tab was selected correctly when removing the active tab.
- Prevented unnecessary state updates.
=> fix(tab): fix active tab switch issue after removal

src/plugins/iconify.ts
现版本的Iconify已经去除了disableCache相关内容，该方法已弃用。
相关PR：https://github.com/iconify/iconify/pull/355
=> optimize(hooks): remove obsolete disabling cache.

README.en_US.md, README.md, package.json
=> docs(deps): update the Vite version of the project description.

src/hooks/common/echarts.ts
部分情况下，图表触发renderChartBySize后，loading不会关闭，例如放在v-if、v-show中的chart，NTab中切换的chart，keepAlive之后的页面的chart。
复现路径：
1. 为home路由添加keepAlive
2. 切换到其他页面，再切回来，会发现loading效果仍然存在
造成这个bug的原因是：
使用这类的方式切换显示之后，useElementSize会侦测到他们的宽高变成0，进而触发针对width与height的watch，导致执行了renderChartBySize，切换回来后页面没有根据这个状态主动再次调用updateOptions（这个情况不应由页面去侦听调用），所以就导致图表数据正常，显示正常，但是loading会一直存在
=> fix(hooks): fixed the issue where loading was not properly closed in some cases.

pnpm-lock.yaml, src/store/modules/auth/index.ts, src/typings/storage.d.ts
本PR解决了不同用户之间登录可能看到彼此标签页内容的安全隐患。通过在用户登出时记录当前用户ID，并在下次登录时比较用户ID是否变更，如果发现不同用户登录则自动清理所有标签页缓存。
1. 添加`recordUserId`函数，用于在用户退出登录时记录当前用户ID到本地存储
2. 添加`checkTabClear`函数，在用户登录成功后检查是否与上次登录用户一致
3. 当检测到不同用户登录时，调用`tabStore.clearTabs()`清理所有非固定标签页
之前系统会在用户退出登录时缓存标签页状态，但没有考虑到用户切换的情况，可能导致新用户看到上一个用户的标签页内容，存在潜在的信息泄露风险。本修复确保了不同用户间的标签页数据隔离。
Closes #721
=> feat(projects): clear tabs cache when switching users.

src/App.vue, src/layouts/modules/theme-drawer/modules/page-fun.vue, src/locales/langs/en-us.ts, src/locales/langs/zh-cn.ts, src/theme/settings.ts, src/typings/app.d.ts
This PR adds a new configuration option that allows users to set username as the watermark content.
- Added `enableUserName: boolean` to watermark settings
- Default value set to `false` for backward compatibility
- When enabled and user is logged in, displays username as watermark
=> feat(projects): add configurable user name watermark option

src/styles/css/global.css
=> fix(projects): ensure proper text color when themes are inverted

.vscode/settings.json
通过单独设置i18n-ally插件的**moduleResolution**配置解决 #780
=> fix(other): 修复当设置moduleResolution为bundler时,i18n-ally不工作问题
