- src/enum/common.ts
> fix(types): 数据类型 EnumDataType.boolean 为 [object Boolean]

- src/AppProvider.vue
> fix(projects): 修复在暗黑模式下第一次进入网页不会触发暗黑模式监听

- .env
- src/router/index.ts
- src/typings/common/env.d.ts
- vite.config.ts
BASE_URL 是内置的关键字，由 base 决定，故修改为 VITE_ 开头的关键字：VITE_APP_BASE_URL
> fix(projects): 修复 BASE_URL 没有生效的问题

- src/utils/auth/user.ts
> docs(other): 注释文案修改

- src/enum/common.ts
- src/utils/auth/user.ts
> perf: refresh-koken命名

- index.html
> feat(projects): HTML lang 修改为 zh-cmn-Hans

- src/components/common/DarkModeContainer.vue
- src/layouts/common/GlobalHeader/components/FullScreen.vue
- src/layouts/common/GlobalHeader/components/GithubSite.vue
- src/layouts/common/GlobalHeader/components/HeaderMenu.vue
- src/layouts/common/GlobalHeader/components/UserAvatar.vue
- src/layouts/common/GlobalHeader/index.vue
- src/layouts/common/GlobalSearch/index.vue
- src/layouts/common/GlobalSider/components/VerticalMixSider/index.vue
- src/layouts/common/GlobalSider/components/VerticalSider/components/VerticalMenu.vue
- src/layouts/common/GlobalSider/components/VerticalSider/index.vue
- src/layouts/common/SettingDrawer/components/PageFunc/index.vue
- src/settings/theme.json
- src/settings/theme.ts
- src/store/modules/theme/index.ts
- src/typings/system.d.ts
#80 theme.sider.inverted & theme.header.inverted 组合使用已达到期望的效果
> feat(layouts): 添加侧边栏/头部的反转模式来增加对比度

- .vscode/extensions.json
> fix(projects): 修复插件不存在的错误提示

- src/layouts/common/GlobalHeader/components/HeaderMenu.vue
> fix: 上下结构，菜单支持横向滚动

- src/components/custom/SvgIcon.vue
- src/layouts/common/GlobalTab/components/TabDetail/components/ContextMenu.vue
- src/store/modules/tab/index.ts
- src/utils/common/icon.ts
[#50 ](https://github.com/honghuangdc/soybean-admin/issues/50)
> feat(tabs): 多页签增加关闭所有

- src/layouts/common/SettingDrawer/components/ThemeColorSelect/components/ColorModal.vue
修复在小屏幕下，系统设置按钮悬浮至模态窗之上的缺陷，提升用户体验
> perf(components): 添加更多主题颜色设置模态窗的层级,z-index为int

- src/store/modules/route/index.ts
> fix(projects): 修复tabs在static路由模式下可以关闭首页

- src/composables/echarts.ts
解决echarts的画布残留问题；将lineOptions的监听模式设为深度监听。
> fix echarts

- commitlint.config.js
[czg 1.4.0更新日志](https://github.com/Zhengqbbb/cz-git/blob/main/CHANGELOG.md)
> refactor(czg): update cz-git,czg breaking changes

- src/composables/echarts.ts
- src/hooks/business/useCountDown.ts
- src/store/subscribe/theme.ts
使用effectScope, onScopeDispose重新定义watch取消监听方式
> refactor(hooks): 重构hook函数取消监听方式

- src/components/custom/IconSelect.vue
> fix(components): 修复iconSelect选择器点击事件失效

- src/utils/router/module.ts
meta order property not working for child element ,
sortRoutes shou be recursive
> fix(projects): sortRoutes recursively

- src/typings/route.d.ts
- src/typings/router.d.ts
not only `/login` claim dynamic path scenario , but also others , eg:/user/1
> fix(projects): not only `/login` claim dynamic path scenario 

- .env-config.ts
- src/typings/env.d.ts
> proxy fail fixc

- README.md
1、将代码仓库表格方式展示，增加预览列
2、二次开发项目内容换行
> 优化readme.md

- src/layouts/common/global-header/components/global-breadcrumb.vue
- src/typings/system.d.ts
> fix(projects): 修复面包屑导航下拉菜单语言显示问题

- src/service/request/instance.ts
防止并发请求时，多次刷新token导致token失效的问题
Closes #255
> feat(auth): 防止多次刷新token

- src/router/modules/management.ts
- src/store/modules/tab/index.ts
v0.10.3
切换tab时，保持页面不刷新，关闭tab重新打开时，重新加载页面。
Closes #
> chore(projects): When tab is switched, keep the page without refreshing

- src/layouts/common/global-search/components/search-modal.vue
- src/layouts/common/global-search/components/search-result.vue
> feat: internationalized menu search

- src/layouts/common/global-search/components/search-modal.vue
> perf(components): Optimize internationalized menu search code

- src/store/modules/auth/index.ts
将登录后欢迎通知的自动关闭时间设置为4500ms，与[antdv](https://github.com/soybeanjs/soybean-admin-antd)保持一致
v1.0-beta
修复登录后欢迎通知不关闭的问题
Closes #293
> fix(projects): Fix welcome notification not closing

- src/store/modules/tab/shared.ts
> fix(projects): Missing default value for tab icon

- src/hooks/common/table.ts
> fix(hooks): Fix Naive Pagination's outdated API

- src/layouts/modules/global-search/index.vue
> style(components): Uniform icon size for header

- src/layouts/modules/global-menu/base-menu.vue
- src/store/modules/route/index.ts
- src/typings/router.d.ts
> feat(projects): Add route meta parameter:fixedQuery

- src/layouts/base-layout/index.vue
> fix(projects):fix invalid footer-height for theme configuration

- src/store/modules/theme/shared.ts
> fix(styles): fix css var is inserted repeatedly

- src/hooks/common/router.ts
- src/store/modules/auth/index.ts
删除useRoutePush中的route导出，使用vue-route来获取当前路由
> feat(hooks): deleting the route export of useRoutePush, use vue-router

- src/components/common/menu-toggler.vue
> fix(projects): text level low. #409

- src/typings/api.d.ts
- src/views/manage/menu/modules/menu-operate-drawer.vue
- 修复菜单`fixedIndexInTab`默认值，允许`null`
> fix(projects): menu fixedIndexInTab default null and Tab fixedIndex

- pnpm-lock.yaml
- src/locales/langs/en-us.ts
- src/locales/langs/zh-cn.ts
- src/router/elegant/imports.ts
- src/router/elegant/routes.ts
- src/router/elegant/transform.ts
- src/typings/elegant-router.d.ts
> Example plugin

- src/store/modules/app/index.ts
修正错误拼写，涉及但不局限于分支`main` + `tauri`
> chore(other): correct spell mistake

- src/views/manage/menu/modules/shared.ts
> fix(projects): Fix secondary directory components is empty

- src/typings/env.d.ts
- src/typings/global.d.ts
> optimize(types): Enhance compatibility of global types

- src/plugins/app.ts
> optimize(utils): Reduce code indentation and improve readability

- src/store/modules/auth/index.ts
- src/store/modules/tab/index.ts
> fix(projects): Fix the issue of abnormal tab caching after logout

- src/typings/components.d.ts
- src/views/manage/role/modules/role-search.vue
- src/views/manage/user/modules/user-search.vue
close #537 
* 用户管理默认收起，角色管理默认展开
https://github.com/user-attachments/assets/55c7b44d-7c8b-4d4e-805a-e626f7a5d185
> feat(projects): Manage search area using collapsed components 

- src/App.vue
- src/layouts/modules/theme-drawer/modules/page-fun.vue
- src/locales/langs/en-us.ts
- src/locales/langs/zh-cn.ts
- src/theme/settings.ts
- src/typings/app.d.ts
- src/typings/components.d.ts
* 主题设置添加`全屏水印`
https://github.com/user-attachments/assets/fdb64b5a-73a7-4b35-bded-2b6c5ee19ccc
> feat(projects): add full screen watermark. close #571

- src/typings/api.d.ts
- src/typings/naive-ui.d.ts
> fix(types): fix the type of TableApiFn

- src/plugins/app.ts
修复获取更新的时候可能遇到的缓存问题，简化代码，不用拿baseURL
> fix(projects): avoid retrieving cached HTML

- build/plugins/index.ts
> optimize(projects): remove defineModel setting，enabled by default

- src/views/_builtin/login/modules/code-login.vue
- src/views/_builtin/login/modules/pwd-login.vue
- src/views/_builtin/login/modules/register.vue
- src/views/_builtin/login/modules/reset-pwd.vue
> feat(projects): login supports accessible operation.

- README.en_US.md
- README.md
docs(projects): :pencil: add element-plus version link
> docs(projects): :pencil: add element-plus version link

- uno.config.ts
presetUno has been displayed as outdated, use presetWind3 instead
> chore(projects): update unocss preset

- README.en_US.md
- README.md
> docs(projects): update README

- .vscode/vue3.code-snippets
支持通过关键词一键生成代码模板，示例：
支持page类型（自动加上一个root element和注释），component类型，script、style和template
> feat(utils): support quick generation of code templates.

- package.json
去除lint-staged，且提交效果与之前一致，typecheck和lint出错均会终止提交
> ci(hooks): remove lint-staged in git hook.

- src/layouts/modules/global-header/index.vue
- src/layouts/modules/theme-drawer/modules/page-fun.vue
- src/locales/langs/en-us.ts
- src/locales/langs/zh-cn.ts
- src/theme/settings.ts
- src/typings/app.d.ts
- 在主题设置中添加全局搜索按钮的显示控制选项
- 更新多语言文件，添加全局搜索按钮显示控制的翻译
- 修改全局头部组件，根据主题设置决定是否显示全局搜索按钮
- 在主题抽屉中添加全局搜索按钮显示控制的开关
> feat(theme): global search button toggle

- README.en_US.md
- README.md
> docs(other): update docs with video tutorial link.

- src/constants/app.ts
- src/theme/settings.ts
> feat(projects): modify the default value of the reset cache policy to  'refresh'.
